#pragma once

#include "common/common.h"
#include "common/Sampling/SamplerCommon.h"
#include "common/Acceleration/AccelerationCommon.h"
#include "common/Scene/Scene.h"
#include "common/Scene/Camera/Camera.h"
#include "common/Scene/Camera/Perspective/PerspectiveCamera.h"
#include "common/Scene/Geometry/Mesh/MeshObject.h"
#include "common/Scene/Lights/Light.h"
#include "common/Scene/Lights/Point/PointLight.h"
#include "common/Scene/Lights/Directional/DirectionalLight.h"
#include "common/Rendering/Material/BlinnPhong/BlinnPhongMaterial.h"
#include "common/Utility/Mesh/Loading/MeshLoader.h"
#include "common/Rendering/Renderer.h"
#include "common/Rendering/Renderer/Forward/ForwardRenderer.h"